### ISSUE TITLE
more robust feature detect

### ISSUE THREAD

**Issue by paulirish** [easy-designs/LocalStorageDB.js#1]
if cookies are disabled this code will throw an error as it stands.
a try/catch mostly fixes things, but you can read the details in here
https://github.com/Modernizr/Modernizr/blob/d4bfec66/modernizr.js#L698-722

**Comment by aarongustafson** [comment]
Thanks for the heads-up Paul. I think I took care of this already (only just saw this issue). The code I used seems to be working fine, but I’ll test a little more to see which works better: https://github.com/easy-designs/LocalStorageDB.js/blob/master/src/LocalStorageDB.js#L108-117
