### ISSUE TITLE
Any examples on how to you loop through and display the data using javascript?

### ISSUE THREAD

**Issue by ygagnon** [easy-designs/LocalStorageDB.js#3]
Would you be able to provide some examples on how someone might loop through and display the data using javascript? I'd like to experiment with this library, but am unsure as to how I'd go about it.

- Yvan

**Comment by aarongustafson** [comment]
This library was built for an app we were working on back in 2011: http://apps.wikihow.com/survivalkit

You can see it used quite a bit in this JS file: http://apps.wikihow.com/survivalkit/js/wikihow.js?v=20120509. Just search for instances of `_DB.SELECT` to get a sense of how you might be able to pull content and loop the results. (poking around the code for and use of `getArticles()` might be a good place to start.)
